### ISSUE TITLE
Phase Two Theme didn't appear to me

### ISSUE THREAD

**Issue by vscatarino** [p2-inc/phasetwo-containers#24]
Hello, Guys!

I'm trying use keycloak with docker compose.
But the option theme phase two didn't appear to me.

![image](https://github.com/p2-inc/phasetwo-containers/assets/20404342/b907ee53-d01c-42e8-8234-43fb905de05a)

docker-compose.yml

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: keycloak
    command: ["start-dev"]
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=xxxx
      - KEYCLOAK_ADMIN_PASSWORD=xxxx
      - KC_HTTP_RELATIVE_PATH=/auth
    depends_on:
      - postgresql
    volumes:
      - './deployments:/opt/keycloak/providers'
volumes:
  postgresql_data:
    driver: local
```

Dockerfile
```
FROM quay.io/phasetwo/phasetwo-keycloak:22.0.1

COPY ./src/policy.jar /opt/keycloak/providers/
 
RUN /opt/keycloak/bin/kc.sh build
```
