### ISSUE TITLE
Fresh docker compose install of keycloak does not work (http errors)

### ISSUE THREAD

**Issue by alexanderhofstaetter** [p2-inc/phasetwo-containers#36]
We use the `quay.io/phasetwo/phasetwo-keycloak` image for our keycloak install.

We started from a completely fresh installation, however, we have errors with the 23.0.7 version of the image.

The problem is: In the admin UI it wont load realms (its loading forever) and we cannot edit any realm settings - it fails with HTTP method not allowed. (see the screenshots)

We use cloudflared as a revery proxy (it works perfectly fine with the original keycloak image `quay.io/keycloak/keycloak`)

![image](https://github.com/p2-inc/phasetwo-containers/assets/6820505/843dfdc5-d760-4259-a511-8b4e5b8ca9e5)
<img width="1703" alt="image" src="https://github.com/p2-inc/phasetwo-containers/assets/6820505/ae9d2cc2-b701-4855-9509-8cf77b7c154d">

The problems seems to be also for 23.0.6 - using 23.0.5 it works perfectly fine.

We use latest docker and docker compose on Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-100-generic x86_64).

To reproduce: simple put the docker-compose.yml and .env file in the same directory and open the admin UI after a `docker compose up`. We see no errors in the log - also -`-log-level=debug` was not helpfull!

**docker-compose.yml**

```
version: "3.8"

services:

  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:23.0.7
    container_name: keycloak
    hostname: keycloak
    restart: always
    networks:
      - default
    depends_on:
      - keycloak_db
    env_file:
      - .env
    command: "start"

  keycloak_db:
    image: postgres:15
    container_name: keycloak_db
    hostname: keycloak_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql

```

**.env**
```
POSTGRES_PASSWORD=password
POSTGRES_USER=keycloak
POSTGRES_DB=keycloak
POSTGRES_INITDB_ARGS="--locale-provider=icu --icu-locale=de-AT"

KC_DB_URL_HOST=keycloak_db
KC_DB_URL_DATABASE=keycloak
KC_DB_USERNAME=keycloak
KC_DB_PASSWORD=password

KC_HOSTNAME=login.example.org

KC_PROXY=edge
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=password
```
