### ISSUE TITLE
Postgres docker-compose example data not persistant

### ISSUE THREAD

**Issue by mihha** [p2-inc/phasetwo-containers#52]
Hi!

I am using your Postgres docker compose example with slight changes for volume tags

```
version: '3'

services:
  postgres:
    image: postgres:11
      # image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_PRODUCTION: true
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB_VENDOR: POSTGRES
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_URL: https://auth.MY_DOMAIN.net
      KC_HOSTNAME_ADMIN_URL: https://auth.MY_DOMAIN.net
      KC_HOSTNAME_PATH: /
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_PROXY_HEADERS: 'xforwarded'
      KC_LOG_LEVEL: INFO
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--spi-email-template-provider=freemarker-plus-mustache", "--spi-email-template-freemarker-plus-mustache-enabled=true", "--spi-theme-cache-themes=false"]
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
```

With this docker compose file, when I stop and start docker again, data in Keycloak is lost and everything is reset to the initial values

I can't figure out what I am doing wrong here

I would be really grateful if someone could check this and point me into the right direction

Thank you all for your attention!

Regards,
Igor

**Comment by xgp** [comment]
Probably need to do something like this:
```yaml
version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11
      # image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_PRODUCTION: true
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB_VENDOR: POSTGRES
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_URL: https://auth.MY_DOMAIN.net
      KC_HOSTNAME_ADMIN_URL: https://auth.MY_DOMAIN.net
      KC_HOSTNAME_PATH: /
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_PROXY_HEADERS: 'xforwarded'
      KC_LOG_LEVEL: INFO
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--spi-email-template-provider=freemarker-plus-mustache", "--spi-email-template-freemarker-plus-mustache-enabled=true", "--spi-theme-cache-themes=false"]
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
```
Can you try that @mihha and PR if that works for you?
