### ISSUE TITLE
have you ever considered mounting cockroachdb certs, instead of using a password and setting up an account?

### ISSUE THREAD

**Issue by lknite** [p2-inc/phasetwo-containers#58]
In a home project I ended up looking at the yaml of cockroachdb-# and copying the initContainer out of there:
```yaml
  initContainers:
  - command:
    - /bin/sh
    - -c
    - '>- cp -p /cockroach/cockroach-certs-prestage/..data/* /cockroach/cockroach-certs/
      && chmod 600 /cockroach/cockroach-certs/*.key && chown 1000581000:1000581000
      /cockroach/cockroach-certs/*.key'
    image: cockroachdb/cockroach:v23.2.2
    imagePullPolicy: IfNotPresent
    name: db-init
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cockroach/cockroach-certs-prestage/
      name: certs
    - mountPath: /cockroach/cockroach-certs/
      name: emptydir
```
and the needed volumes:
```yaml
volumes:
  - name: datadir
    persistentVolumeClaim:
      claimName: datadir-cockroachdb-0
  - emptyDir: {}
    name: emptydir
  - name: certs
    projected:
      defaultMode: 400
      sources:
      - secret:
          items:
          - key: ca.crt
            mode: 504
            path: ca.crt
          - key: tls.crt
            mode: 504
            path: node.crt
          - key: tls.key
            mode: 400
            path: node.key
          name: cockroachdb-node
      - secret:
          items:
          - key: tls.crt
            mode: 504
            path: client.root.crt
          - key: tls.key
            mode: 400
            path: client.root.key
          name: cockroachdb-root
```

and then, in my code I connected to cockroachdb using the certs instead of username/password, like so:

```go
	connection := fmt.Sprint(
		" host="+svcHost,
		" port="+svcPort,
		" sslmode=require",
		" sslrootcert=/cockroach/cockroach-certs/ca.crt",
		" sslkey=/cockroach/cockroach-certs/client.root.key",
		" sslcert=/cockroach/cockroach-certs/client.root.crt",
	)
```

And ... it just works, no password needed.

This would ease deployment, skipping the steps necessary to create a user, set its password, grant it the needed access, and set the password in keycloak.

What do you think?

Note, I'm using the cockroachdb-operator to deploy clusters, not sure if that matters ...
